# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semiont < Formula
  desc "Local Semiont stack launcher — drives Apple container, Docker, or Podman"
  homepage "https://github.com/The-AI-Alliance/semiont"
  version "0.6.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-AI-Alliance/semiont/releases/download/v0.6.10/semiont_0.6.10_darwin_amd64.tar.gz"
      sha256 "c3be9bbcb09374317258cdb529c503a99b7ddc47a4bdaf590290e23e961a4edf"

      define_method(:install) do
        bin.install "semiont"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-AI-Alliance/semiont/releases/download/v0.6.10/semiont_0.6.10_darwin_arm64.tar.gz"
      sha256 "5053930af44fd7f9f6bc327db1f343baec4ab4b1d1ff9238f10546fda4d07eae"

      define_method(:install) do
        bin.install "semiont"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Alliance/semiont/releases/download/v0.6.10/semiont_0.6.10_linux_amd64.tar.gz"
      sha256 "9161d87b1632c7801838bb3fe6f1676095c22514487b2b3f02a6901542fdf085"
      define_method(:install) do
        bin.install "semiont"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Alliance/semiont/releases/download/v0.6.10/semiont_0.6.10_linux_arm64.tar.gz"
      sha256 "a01f9a8966cb408e8eb168dbdff0b3c1905a232a7449cc9ec78f758c84701212"
      define_method(:install) do
        bin.install "semiont"
      end
    end
  end

  def caveats
    <<~EOS
      Next:
        semiont init        make a new knowledge base here, or clone one
        semiont start       run its stack
        semiont settings    where secrets come from and where they are kept,
                            the container runtime, and the rest
      A knowledge base's secrets are kept in plain files by default, which are
      not secure: for development only. To keep every new knowledge base's
      secrets in 1Password:
        semiont settings secret-store --default op://<vault>
    EOS
  end

  test do
    system "#{bin}/semiont", "version"
  end
end
