# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semiont < Formula
  desc "Local Semiont stack launcher — drives Apple container, Docker, or Podman"
  homepage "https://github.com/The-AI-Alliance/semiont"
  version "0.5.31"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-AI-Alliance/semiont/releases/download/v0.5.31/semiont_0.5.31_darwin_amd64.tar.gz"
      sha256 "5f515fd4390249dc756cc12923b8d078cb1f817650b0b284d5291a716fbea86b"

      define_method(:install) do
        bin.install "semiont"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-AI-Alliance/semiont/releases/download/v0.5.31/semiont_0.5.31_darwin_arm64.tar.gz"
      sha256 "a843785b25b78b6f0062d296ae60dda15d01a7797e233bbf0d4c93abd52c3601"

      define_method(:install) do
        bin.install "semiont"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Alliance/semiont/releases/download/v0.5.31/semiont_0.5.31_linux_amd64.tar.gz"
      sha256 "b9f0457a72dfa97534912dcf77911f88b649fc6c684053aef47629bb916b3a80"
      define_method(:install) do
        bin.install "semiont"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Alliance/semiont/releases/download/v0.5.31/semiont_0.5.31_linux_arm64.tar.gz"
      sha256 "87d2ab65413e39c57d668eab76b31d839068f3aaad4932dbace0561f81016992"
      define_method(:install) do
        bin.install "semiont"
      end
    end
  end

  test do
    system "#{bin}/semiont", "version"
  end
end
